root = "."
tmp_dir = "tmp"

[build]
# jsut plain old shell command. you could use `make` as well.
cmd = "go build -o ./tmp/main ."
# binary file yields from `cmd`.
bin = "tmp/main"

full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 80"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "vender", "tmp"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
delay = 1000 #ms 
stop_on_error = true
send_interrupt = false
kill_delay = 500 #ms 

[log]
time = false

[color]
main = "red"
watcher = "blue"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true